### ISSUE TITLE
Indentação

### ISSUE THREAD

**Issue by rafaelgalle** [andrelsmelo/exercicio-javascript#2]
https://github.com/andrelsmelo/exercicio-javascript/blob/e74e8f50a2147941e13de7282344006066487160/src/script.js#L186

Indentação errada.

**Comment by rafaelgalle** [comment]
Tem muitos outros lugares no código com indentação errada, bom revisar todos eles.

**Comment by andrelsmelo** [comment]
Ajustado indentação, removidos espaços desnecessários, atribuído padrão aos ifs, desta forma:

`if(<conteudo>) {<bloco>}`
