### ISSUE TITLE
Nomenclatura 

### ISSUE THREAD

**Issue by rafaelgalle** [andrelsmelo/exercicio-javascript#4]
https://github.com/andrelsmelo/exercicio-javascript/blob/e74e8f50a2147941e13de7282344006066487160/src/script.js#L270

Oq é form1, form2 e form3?
Oq faz o next, next2, back e back2?

Procure dar nomes que facilitem a identificação das variáveis e funções, 
se é um formulário de cadastros, formulário de endereços.
se é um botão que avança para o formulário de endereços ou volta para o formulário de pessoa.

**Comment by andrelsmelo** [comment]
Ajustado nomenclaturas de botoes e formulários para melhor identificação
