### ISSUE TITLE
Classes inúteis 

### ISSUE THREAD

**Issue by rafaelgalle** [andrelsmelo/exercicio-javascript#5]
https://github.com/andrelsmelo/exercicio-javascript/blob/e74e8f50a2147941e13de7282344006066487160/src/script.js#L50

Esse tipo de validação poderia estar na própria classe, tanto para o Person quanto para o Address, é responsabilidade delas, assim evitaria criar uma função antes de instanciar a classe só pra isso, e se fosse utilizar esse classe em outro local também evitaria duplicar essa validação, já que estaria dentro da própria classe.

Hoje as classes não estão fazendo nada, se for assim melhor nem usar classes então.

**Comment by andrelsmelo** [comment]
Inserido funções de validação dentro das classes sendo chamadas antes de registrar
